version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-reactive-processor
    ports:
      - "9092:9092"
    environment:
#      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  eureka:
   build: ./eureka/
   restart: always
   ports:
     - "8761:8761"
   environment:
     SPRING_PROFILES_ACTIVE: docker

  gateway:
   depends_on:
     - eureka
   build: ./gateway/
   ports:
     - "8080:8080"
   restart: always
   environment:
     SPRING_PROFILES_ACTIVE: docker
     EUREKA_HOST: eureka
     REDIS_HOST: redis

  counter-service:
    depends_on:
      - eureka
      - kafka
      - mongo
      - redis
    build: ./counter-service/
    ports:
      - "9010"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_HOST: eureka
      KAFKA_HOST: kafka
      MONGO_HOST: mongo
      REDIS_HOST: redis

  nginx:
     image: nginx:latest
     ports:
       - "80:80"
     restart: always
     volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  data-volume: