server:
  port: 8761

spring:
  application:
      name: eureka
  profiles:
    active: local

---
spring:
  profiles: local

eureka:
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 3000
    renewalPercentThreshold: 0.49
    response-cache-update-interval-ms: 1000
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: docker

eureka:
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 3000
    renewalPercentThreshold: 0.49
    response-cache-update-interval-ms: 1000
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
